# This file is part of Quipper. Copyright (C) 2011-2013. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = Main.hs
TARGET = QCLParser
MAIN = Main.hs
MAIN_IS = Programs.QCLParser.Main
SUBDIR = Programs/QCLParser
BASEDIR = ../..
EXTRA_DIST = README bwt.qcl QCL-bwt-n4.out

include $(BASEDIR)/Makefile.common
