# This file is part of Quipper. Copyright (C) 2011-2014. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================

QCLParser Main.hi: Main.hs ../../quipper/Quipper.hs ../../quipper/Quipper/Monad.hs ../../quipper/Quipper/Generic.hs ../../quipper/Quipper/QData.hs ../../quipper/Quipper/QClasses.hs ../../quipper/Quipper/Control.hs ../../quipper/Quipper/CircLifting.hs ../../quipper/Quipper/Transformer.hs ../../quipper/Quipper/Circuit.hs ../../quipper/Quipper/Classical.hs ../../quipper/Quipper/Printing.hs ../../quipper/Quipper/Labels.hs ../../Libraries/Template.hs ../../Libraries/Auxiliary.hs ../../Libraries/Tuple.hs ../../Libraries/Typeable.hs ../../Libraries/Template/Lifting.hs ../../Libraries/Template/Auxiliary.hs ../../Libraries/Template/LiftQ.hs ../../Libraries/Template/ErrorMsgQ.hs
Main.hi: Main.hs ../../quipper/Quipper.hi
../../quipper/Quipper.hi: ../../quipper/Quipper.hs ../../quipper/Quipper/Monad.hi ../../quipper/Quipper/Generic.hi ../../quipper/Quipper/QData.hi ../../quipper/Quipper/QClasses.hi ../../quipper/Quipper/Control.hi ../../quipper/Quipper/CircLifting.hi ../../quipper/Quipper/Transformer.hi ../../quipper/Quipper/Circuit.hi ../../quipper/Quipper/Classical.hi ../../quipper/Quipper/Printing.hi ../../quipper/Quipper/Labels.hi ../../Libraries/Template.hi ../../Libraries/Auxiliary.hi
../../quipper/Quipper/Monad.hi: ../../quipper/Quipper/Monad.hs ../../quipper/Quipper/Circuit.hi ../../Libraries/Auxiliary.hi ../../quipper/Quipper/Transformer.hi ../../quipper/Quipper/Control.hi
../../quipper/Quipper/Circuit.hi: ../../quipper/Quipper/Circuit.hs ../../Libraries/Auxiliary.hi
../../Libraries/Auxiliary.hi: ../../Libraries/Auxiliary.hs
../../quipper/Quipper/Transformer.hi: ../../quipper/Quipper/Transformer.hs ../../quipper/Quipper/Circuit.hi ../../Libraries/Auxiliary.hi
../../quipper/Quipper/Control.hi: ../../quipper/Quipper/Control.hs ../../quipper/Quipper/Circuit.hi ../../Libraries/Tuple.hi
../../Libraries/Tuple.hi: ../../Libraries/Tuple.hs
../../quipper/Quipper/Generic.hi: ../../quipper/Quipper/Generic.hs ../../quipper/Quipper/Circuit.hi ../../quipper/Quipper/Monad.hi ../../Libraries/Auxiliary.hi ../../Libraries/Tuple.hi ../../quipper/Quipper/Transformer.hi ../../quipper/Quipper/Control.hi ../../quipper/Quipper/QData.hi
../../quipper/Quipper/QData.hi: ../../quipper/Quipper/QData.hs ../../quipper/Quipper/Monad.hi ../../Libraries/Auxiliary.hi ../../Libraries/Tuple.hi ../../quipper/Quipper/Labels.hi ../../quipper/Quipper/Transformer.hi ../../quipper/Quipper/Control.hi ../../Libraries/Typeable.hi
../../quipper/Quipper/Labels.hi: ../../quipper/Quipper/Labels.hs ../../quipper/Quipper/Circuit.hi ../../quipper/Quipper/Monad.hi ../../Libraries/Auxiliary.hi ../../Libraries/Tuple.hi ../../quipper/Quipper/Transformer.hi
../../Libraries/Typeable.hi: ../../Libraries/Typeable.hs
../../quipper/Quipper/QClasses.hi: ../../quipper/Quipper/QClasses.hs ../../quipper/Quipper/Generic.hi ../../quipper/Quipper/QData.hi ../../quipper/Quipper/Monad.hi
../../quipper/Quipper/CircLifting.hi: ../../quipper/Quipper/CircLifting.hs ../../quipper/Quipper/Monad.hi ../../quipper/Quipper/Monad.hi ../../quipper/Quipper/Circuit.hi ../../quipper/Quipper/Generic.hi ../../quipper/Quipper/QData.hi ../../Libraries/Auxiliary.hi ../../quipper/Quipper/Control.hi ../../quipper/Quipper/QClasses.hi ../../Libraries/Template.hi
../../Libraries/Template.hi: ../../Libraries/Template.hs ../../Libraries/Template/Lifting.hi ../../Libraries/Template/Auxiliary.hi
../../Libraries/Template/Lifting.hi: ../../Libraries/Template/Lifting.hs ../../Libraries/Template/LiftQ.hi
../../Libraries/Template/LiftQ.hi: ../../Libraries/Template/LiftQ.hs ../../Libraries/Template/ErrorMsgQ.hi ../../Libraries/Template/ErrorMsgQ.hi
../../Libraries/Template/ErrorMsgQ.hi: ../../Libraries/Template/ErrorMsgQ.hs
../../Libraries/Template/Auxiliary.hi: ../../Libraries/Template/Auxiliary.hs ../../Libraries/Auxiliary.hi
../../quipper/Quipper/Classical.hi: ../../quipper/Quipper/Classical.hs ../../quipper/Quipper/Generic.hi ../../quipper/Quipper/QData.hi ../../quipper/Quipper/Monad.hi ../../quipper/Quipper/Control.hi ../../quipper/Quipper/Transformer.hi
../../quipper/Quipper/Printing.hi: ../../quipper/Quipper/Printing.hs ../../Libraries/Auxiliary.hi ../../quipper/Quipper/Circuit.hi ../../quipper/Quipper/Generic.hi ../../quipper/Quipper/Monad.hi ../../quipper/Quipper/QData.hi
