# This file is part of Quipper. Copyright (C) 2011-2013. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = GSE.hs Main.hs GSEData.hs JordanWigner.hs
TARGET = gse
MAIN = Main.hs
MAIN_IS = Algorithms.GSE.Main
SUBDIR = Algorithms/GSE
BASEDIR = ../..
EXTRA_DIST = h_1e_ascii h_2e_ascii

include $(BASEDIR)/Makefile.common
