# This file is part of Quipper. Copyright (C) 2011-2014. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = SmithReduction.hs CL.hs Test.hs Types.hs		\
	  Auxiliary.hs RegulatorClassical.hs RegulatorQuantum.hs	\
	  Main.hs
TARGET = cl
MAIN = Main.hs
MAIN_IS = Algorithms.CL.Main
SUBDIR = Algorithms/CL
BASEDIR = ../..

include $(BASEDIR)/Makefile.common
