# This file is part of Quipper. Copyright (C) 2011-2013. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = BWT.hs Simulate.hs Alternative.hs Template.hs Definitions.hs Main.hs
TARGET = bwt
MAIN = Main.hs
MAIN_IS = Algorithms.BWT.Main
SUBDIR = Algorithms/BWT
BASEDIR = ../..

include $(BASEDIR)/Makefile.common
