# This file is part of Quipper. Copyright (C) 2011-2013. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = Definitions.hs QWTFP.hs Oracle.hs Alternatives.hs Simulate.hs Main.hs
TARGET = tf
MAIN = Main.hs
MAIN_IS = Algorithms.TF.Main
SUBDIR = Algorithms/TF
BASEDIR = ../..

include $(BASEDIR)/Makefile.common
