# This file is part of Quipper. Copyright (C) 2011-2013. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================

newsynth Main.hi: Main.hs ../../Libraries/Synthesis/Newsynth.hs ../../Libraries/Synthesis/SymReal.hs ../../Libraries/Synthesis/CliffordT.hs ../../Libraries/Synthesis/Ring.hs ../../Libraries/Synthesis/Matrix.hs ../../Libraries/Synthesis/LaTeX.hs ../../Libraries/CommandLine.hs ../../Libraries/Synthesis/Ring/FixedPrec.hs ../../Libraries/Synthesis/EuclideanDomain.hs ../../Libraries/Synthesis/ArcTan2.hs ../../Libraries/Synthesis/Clifford.hs ../../Libraries/Synthesis/MultiQubitSynthesis.hs ../../Libraries/Auxiliary.hs
Main.hi: Main.hs ../../Libraries/Synthesis/Newsynth.hi ../../Libraries/Synthesis/SymReal.hi ../../Libraries/Synthesis/CliffordT.hi ../../Libraries/Synthesis/Ring.hi ../../Libraries/Synthesis/Matrix.hi ../../Libraries/Synthesis/LaTeX.hi ../../Libraries/CommandLine.hi
../../Libraries/Synthesis/Newsynth.hi: ../../Libraries/Synthesis/Newsynth.hs ../../Libraries/Synthesis/Ring.hi ../../Libraries/Synthesis/Ring/FixedPrec.hi ../../Libraries/Synthesis/Matrix.hi ../../Libraries/Synthesis/CliffordT.hi ../../Libraries/Synthesis/EuclideanDomain.hi ../../Libraries/Synthesis/SymReal.hi
../../Libraries/Synthesis/Ring.hi: ../../Libraries/Synthesis/Ring.hs
../../Libraries/Synthesis/Ring/FixedPrec.hi: ../../Libraries/Synthesis/Ring/FixedPrec.hs ../../Libraries/Synthesis/Ring.hi
../../Libraries/Synthesis/Matrix.hi: ../../Libraries/Synthesis/Matrix.hs ../../Libraries/Synthesis/Ring.hi
../../Libraries/Synthesis/CliffordT.hi: ../../Libraries/Synthesis/CliffordT.hs ../../Libraries/Synthesis/Ring.hi ../../Libraries/Synthesis/Matrix.hi ../../Libraries/Synthesis/Clifford.hi ../../Libraries/Synthesis/MultiQubitSynthesis.hi
../../Libraries/Synthesis/Clifford.hi: ../../Libraries/Synthesis/Clifford.hs
../../Libraries/Synthesis/MultiQubitSynthesis.hi: ../../Libraries/Synthesis/MultiQubitSynthesis.hs ../../Libraries/Synthesis/Matrix.hi ../../Libraries/Synthesis/Ring.hi
../../Libraries/Synthesis/EuclideanDomain.hi: ../../Libraries/Synthesis/EuclideanDomain.hs ../../Libraries/Synthesis/Ring.hi
../../Libraries/Synthesis/SymReal.hi: ../../Libraries/Synthesis/SymReal.hs ../../Libraries/Synthesis/ArcTan2.hi
../../Libraries/Synthesis/ArcTan2.hi: ../../Libraries/Synthesis/ArcTan2.hs
../../Libraries/Synthesis/LaTeX.hi: ../../Libraries/Synthesis/LaTeX.hs ../../Libraries/Synthesis/CliffordT.hi ../../Libraries/Synthesis/MultiQubitSynthesis.hi ../../Libraries/Synthesis/Ring.hi ../../Libraries/Synthesis/Matrix.hi ../../Libraries/Synthesis/SymReal.hi
../../Libraries/CommandLine.hi: ../../Libraries/CommandLine.hs ../../Libraries/Auxiliary.hi
../../Libraries/Auxiliary.hi: ../../Libraries/Auxiliary.hs
