# This file is part of Quipper. Copyright (C) 2011-2013. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = Fowler.hs Main.hs
TARGET = newsynth
MAIN = Main.hs
MAIN_IS = Programs.Synthesis.Main
SUBDIR = Programs/Synthesis
BASEDIR = ../..
EXTRA_DIST = parallel.sh

include $(BASEDIR)/Makefile.common
