# This file is part of Quipper. Copyright (C) 2011-2013. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = Main.hs CircLiftingImport.hs \
 TemplateOracle.hs QDouble.hs	\
 RealFunc.hs QLS.hs QSignedIntAux.hs \
 QSignedInt.hs Utils.hs

TARGET = qls
MAIN = Main.hs
MAIN_IS = Algorithms.QLS.Main
SUBDIR = Algorithms/QLS
BASEDIR = ../..



include $(BASEDIR)/Makefile.common
