# This file is part of Quipper. Copyright (C) 2011-2014. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MULTIPLE_MAINS = yes
NODOC = yes
TARGET = Approximate ASCII Binary CliffordT Depth EPS Exact GateCount	\
         PDF Preview Simulate Standard Strict TrimControls Unbox
MODULES = $(TARGET:%=%.hs)
SUBDIR = Programs/Tools
SUBPACKAGE = tools
BASEDIR = ../..

include $(BASEDIR)/Makefile.common
