# This file is part of Quipper. Copyright (C) 2011-2014. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MULTIPLE_MAINS = yes
NODOC = yes
TARGET = Test1 Test2
MODULES = Test1.hs Test2.hs Test1Import.hs Test2Import.hs
SUBDIR = tests/template
SUBPACKAGE = template-tests
BASEDIR = ../..

include $(BASEDIR)/Makefile.common
