# This file is part of Quipper. Copyright (C) 2011-2014. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = BooleanFormula.hs Hex.hs QuantumIf.hs HexBoard.hs Testing.hs Main.hs
TARGET = bf
MAIN = Main.hs
MAIN_IS = Algorithms.BF.Main
SUBDIR = Algorithms/BF
BASEDIR = ../..

include $(BASEDIR)/Makefile.common
