# This file is part of Quipper. Copyright (C) 2011-2013. Please see the
# file COPYRIGHT for a list of authors, copyright holders, licensing,
# and other details. All rights reserved.
# 
# ======================================================================


MODULES = Main.hs Definitions.hs USV.hs Simulate.hs
TARGET = usv
MAIN = Main.hs
MAIN_IS = Algorithms.USV.Main
SUBDIR = Algorithms/USV
BASEDIR = ../..

include $(BASEDIR)/Makefile.common
